# Last manual image build: Mon May 5 17:57:37 EEST 2025
pipelines:
  test:
    blubberfile: blubber.yaml
    stages:
      - name: test-backend
        build: test
        run: true
      - name: test-pagelib
        build: test-pagelib
        run: true
  publish:
    blubberfile: blubber.yaml
    stages:
      - name: test
        build: test
        run: true
      - name: production
        build: production
        publish:
          image: true
        promote:
          - chart: mobileapps
