const newsHtml1 = '<!--June 20 --> In <a rel="mw:WikiLink" href="./Basketball" title="Basketball" id="mwBA">basketball</a>, the <a rel="mw:WikiLink" href="./Cleveland_Cavaliers" title="Cleveland Cavaliers" id="mwBQ">Cleveland Cavaliers</a> defeat the <a rel="mw:WikiLink" href="./Golden_State_Warriors" title="Golden State Warriors" id="mwBg">Golden State Warriors</a> to win the <b id="mwBw"><a rel="mw:WikiLink" href="./2016_NBA_Finals" title="2016 NBA Finals" id="mwCA">NBA Finals</a></b> <i id="mwCQ">(<a rel="mw:WikiLink" href="./Bill_Russell_NBA_Finals_Most_Valuable_Player_Award" title="Bill Russell NBA Finals Most Valuable Player Award" id="mwCg">MVP</a> <a rel="mw:WikiLink" href="./LeBron_James" title="LeBron James" id="mwCw">LeBron James</a> pictured)</i>.';
const newsHtml2 = '<!--June 24 --> After the United Kingdom <b id="mwCA"><a rel="mw:WikiLink" href="./United_Kingdom_European_Union_membership_referendum,_2016" title="United Kingdom European Union membership referendum, 2016" id="mwCQ" class="feednewslink">votes to leave</a></b> the <a rel="mw:WikiLink" href="./European_Union" title="European Union" id="mwCg" class="feednewslink">European Union</a>, <a rel="mw:WikiLink" href="./British_Prime_Minister" title="British Prime Minister" id="mwCw" class="feednewslink">British Prime Minister</a> <b id="mwDA"><a rel="mw:WikiLink" href="./David_Cameron" title="David Cameron" id="mwDQ" class="feednewslink">David Cameron</a></b> <i id="mwDg">(pictured)</i> announces he will resign by October.';

const cleanNewsHtml1 = '<!--June 20 --> In <a rel="mw:WikiLink" href="./Basketball" title="Basketball" id="mwBA">basketball</a>, the <a rel="mw:WikiLink" href="./Cleveland_Cavaliers" title="Cleveland Cavaliers" id="mwBQ">Cleveland Cavaliers</a> defeat the <a rel="mw:WikiLink" href="./Golden_State_Warriors" title="Golden State Warriors" id="mwBg">Golden State Warriors</a> to win the <b id="mwBw"><a rel="mw:WikiLink" href="./2016_NBA_Finals" title="2016 NBA Finals" id="mwCA">NBA Finals</a></b>.';
const cleanNewsHtml2 = '<!--June 24 --> After the United Kingdom <b id=\"mwCA\"><a rel=\"mw:WikiLink\" href=\"./United_Kingdom_European_Union_membership_referendum,_2016\" title=\"United Kingdom European Union membership referendum, 2016\" id=\"mwCQ\" class=\"feednewslink\">votes to leave</a></b> the <a rel=\"mw:WikiLink\" href=\"./European_Union\" title=\"European Union\" id=\"mwCg\" class=\"feednewslink\">European Union</a>, <a rel=\"mw:WikiLink\" href=\"./British_Prime_Minister\" title=\"British Prime Minister\" id=\"mwCw\" class=\"feednewslink\">British Prime Minister</a> <b id=\"mwDA\"><a rel=\"mw:WikiLink\" href=\"./David_Cameron\" title=\"David Cameron\" id=\"mwDQ\" class=\"feednewslink\">David Cameron</a></b> announces he will resign by October.';

module.exports = {
    newsHtml1: newsHtml1,
    newsHtml2: newsHtml2,
    cleanNewsHtml1: cleanNewsHtml1,
    cleanNewsHtml2: cleanNewsHtml2
}