#!/usr/bin/env node

'use strict';

const fs = require('fs');
const dateUtil = require('../../lib/dateUtil');
const preq = require('preq');
const NEWS_SITES = require('../../etc/feed/news-sites');

const timestamp = dateUtil.formatISODate(new Date());

for (const lang of Object.keys(NEWS_SITES)) {
    const uri = `https://${lang}.wikipedia.org/api/rest_v1/page/html/${encodeURIComponent(NEWS_SITES[lang].title)}`;
    const filename = `news-site-${lang}-${timestamp}.htm`;
    preq
      .get({ uri })
      .then((rsp) => fs.writeFile(filename, rsp.body, (err) => { if (err) { throw err; } }))
      .catch((err) => {
          process.stderr.write(err.toString());
          process.exit(1);
      });
}
